# commit to be tagged for the new release
commit = "HEAD"

github_repo = "siderolabs/talos-backup"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"
project_name = "talos-backup"

# previous = -
# pre_release = true

# [notes]
